project:
  output-dir: _output
  type: website

website:
  title: "Aerial Mzansi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: https://shiny.aerialmzansi.com/
        text: Shiny Dashboard
    right:
      - icon: github
        href: https://github.com/luisdza/aerialmzansi-website
  twitter-card: true

format:
  html:
    theme: cosmo
    code-link: true
    include-in-header: "plausible.html"
    callout-appearance: simple
    toc: true
    author-meta: "Luis de Sousa"
    description-meta: "Aerial Mzansi"
