---
title: "About"
editor: visual
---

# Images generated for the points below

```{r, message=FALSE, echo=FALSE}
library(magrittr)

# Connect to Azure blob
blob_endp_url <- "https://aerialmzansi.blob.core.windows.net/"
endp <- AzureStor::blob_endpoint(blob_endp_url, key=Sys.getenv("AZURE_BLOB_ACCESS_KEY"))

# Select image container
cont <- AzureStor::blob_container(endp, "images")

# Image list
blob_image_names <- data.frame(image_name = AzureStor::list_blobs(cont, info="name"))

blob_image_names <- blob_image_names %>% 
  dplyr::arrange(desc(image_name)) %>% 
  dplyr::mutate(file_name = stringr::str_replace(image_name,".jpeg","")) %>%
  tidyr::separate(file_name, c("date","time","long","lat"), sep = "_")

# World map
world <- rnaturalearth::ne_countries(scale = "small", returnclass = "sf", country = "South Africa")

sites <- sf::st_as_sf(data.frame(longitude = blob_image_names$long, latitude = blob_image_names$lat),
                       coords = c("longitude", "latitude"), 
                       crs = 4326,
                       agr = "constant")

ggplot2::ggplot(data = world) +
  ggplot2::geom_sf() +
  ggplot2::geom_sf(data = sites, size = 1, shape = 21, fill = "darkred") +
  ggplot2::coord_sf(xlim = c(16, 33), ylim = c(-35, -22), expand = FALSE)
```
# About Aerial Mzansi

[Luis de Sousa](https://twitter.com/luis_de_sousa) created Aerial Mzansi. The source code for the project can be found [here](https://github.com/luisdza/aerialmzansi).

Every 4 hours, a new image is automatically uploaded to the website.

# Purpose

## 1. Art!

The twitter account [Textures of Utah](https://mobile.twitter.com/texturesofut) initially inspired me. I found there was a whole [mapbotverse](https://mobile.twitter.com/i/lists/1492559073287581707) with similar implementations for different countries. [Matt Dray](https://twitter.com/mattdray) started the mapbotverse with the [londonmapbot](https://twitter.com/londonmapbot) project.

I live in Johannesburg, the largest city in South Africa, where space is considered a premium. While generating images of the South African landscape, I realised how sparsely populated the country is.

## 2. Using new technologies

I've implemented the mapbot concept using technologies that I wanted to learn more about:

1.  [Github Actions](https://github.com/features/actions) -- Automate the whole build and deploy process to Github pages.

2.  [AzureStor](https://cran.r-project.org/web/packages/AzureStor/index.html) -- After generating the images, they are stored in an Azure blob.

3.  [Quarto](https://quarto.org/) -- Creating a website with dynamic content.

4.  [Quarto Addins](https://quarto.org/docs/extensions/) -- Lightbox, to create lightbox treatments for images in HTML documents.

## 3. Working in public

From Austin Kleon's book, [Show Your Work!](https://www.amazon.com/Show-Your-Work-Austin-Kleon/dp/076117897X)

1.  Process -\> Progress.

2.  Sharing \> Self-promotion.

3.  Share \<\> Learn. Building an audience for what you do creates a valuable feedback loop.

# Special Thanks

A popular African proverb is, "It takes a village to raise a child", which holds in my case. There are too many people to mention individually.I want to thank everyone with whom I've discussed Areal Mzansi with and all the open-source authors whose projects I've built it on top of.
